# Ngôn ngữ sử dụng
language: node_js

# Các phiên bản Node.js cần kiểm tra
node_js:
  - 16
  - 18

# Chỉ định nhánh để chạy pipeline
branches:
  only:
    - src

# Cài đặt các dependencies trước khi chạy các lệnh test
install:
  - npm install

# Lệnh chạy test
script:
  - npm run

# Cấu hình cache để tăng tốc độ build
cache:
  directories:
    - node_modules

