apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-test
spec:
  selector:
    matchLabels:
      run: frontend-test
  replicas: 2
  template:
    metadata:
      labels:
        run: frontend-test
    spec:
      containers:
        - name: frontend-test
          image: dockerhub-linhhm9/udagram-frontend:latest1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    service: frontend