name: Build and Push Docker Image

on:
  push:
    branches:
      - src
  pull_request:
    branches:
      - src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code từ GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t linhhm9/udagram-frontend ./udagram-frontend
          docker build -t linhhm9/udagram-api-feed ./udagram-api-feed
          docker build -t linhhm9/udagram-api-user ./udagram-api-user
          docker build -t linhhm9/reverseproxy ./udagram-reverseproxy

      # Đăng nhập Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push Docker image lên Docker Hub
      - name: Push Docker image
        run: |
          docker push linhhm9/udagram-frontend
          docker push linhhm9/udagram-api-feed
          docker push linhhm9/udagram-api-user
          docker push linhhm9/reverseproxy
